title: FOSS CTF Bootcamp
description: Beginner-friendly CTF challenges and writeups, built for our campus CTF bootcamp.
theme: jekyll-theme-cayman

# Used by the Cayman theme for the header banner
show_downloads: false

repository: "adharshio/ctf-bootcamp-writeups"

# Simple site-wide nav data used by index.md
challenges:
  - title: "Wiki Backup Leak"
    category: "Network Forensics"
    difficulty: "Beginner"
    summary: "Find a flag split across an HTTP request header and response body inside a packet capture."
    link: /challenges/wiki-backup-leak/
  - title: "Perfect Picture Secret"
    category: "Cryptography"
    difficulty: "Beginner"
    summary: "We intercepted a scrambled transmission and an image file (challenge.png) from an unencrypted channel.
      Decode the message, and retrieve the flag!
      Ciphertext:c2drdXRhM3l1MGUzX3YwX2owNTVfYTU1dTN9"
    link: /challenges/picture-perfect-secret/
  - title: "Unclaimed Luggage"
    category: "Forensics & OSINT"
    difficulty: "Beginner"
    summary: "A suspicious black suitcase was spotted abandoned near a tea shop. Naturally, instead of opening it like normal people, our intel team took a picture of it and ran away."
    link: /challenges/unclaimed-luggage/

markdown: kramdown
plugins:
  - jekyll-relative-links
